site_name: DnevnikRuAPI
nav:
    - Начало: index.md
    - Варианты использования: using.md
    - Документация по методам дневник.ру: methods.md
theme:
  name: 'material'

repo_name: 'kesha1225/DnevnikRuAPI'
repo_url: 'https://github.com/kesha1225/DnevnikRuAPI'