site_name: KunAPIPy
nav:
    - Начало: index.md
    - Использование: using.md
    - Документация по методам kundelik.kz: methods.md
theme:
  name: 'material'

repo_name: 'Bs0Dd/KunAPIPy'
repo_url: 'https://github.com/Bs0Dd/KunAPIPy'
